// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TODO: Here and everywhere, s/Session/Actor to align with the glossary.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: ateapi.proto

package ateapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor_Status int32

const (
	Actor_STATUS_UNSPECIFIED Actor_Status = 0
	Actor_STATUS_RESUMING    Actor_Status = 1
	Actor_STATUS_RUNNING     Actor_Status = 2
	Actor_STATUS_SUSPENDING  Actor_Status = 3
	Actor_STATUS_SUSPENDED   Actor_Status = 4
)

// Enum value maps for Actor_Status.
var (
	Actor_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RESUMING",
		2: "STATUS_RUNNING",
		3: "STATUS_SUSPENDING",
		4: "STATUS_SUSPENDED",
	}
	Actor_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_RESUMING":    1,
		"STATUS_RUNNING":     2,
		"STATUS_SUSPENDING":  3,
		"STATUS_SUSPENDED":   4,
	}
)

func (x Actor_Status) Enum() *Actor_Status {
	p := new(Actor_Status)
	*p = x
	return p
}

func (x Actor_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actor_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ateapi_proto_enumTypes[0].Descriptor()
}

func (Actor_Status) Type() protoreflect.EnumType {
	return &file_ateapi_proto_enumTypes[0]
}

func (x Actor_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actor_Status.Descriptor instead.
func (Actor_Status) EnumDescriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{0, 0}
}

type Actor struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActorId                string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Version                int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	Status                 Actor_Status           `protobuf:"varint,5,opt,name=status,proto3,enum=ateapi.Actor_Status" json:"status,omitempty"`
	AteomPodNamespace      string                 `protobuf:"bytes,6,opt,name=ateom_pod_namespace,json=ateomPodNamespace,proto3" json:"ateom_pod_namespace,omitempty"`
	AteomPodName           string                 `protobuf:"bytes,7,opt,name=ateom_pod_name,json=ateomPodName,proto3" json:"ateom_pod_name,omitempty"`
	AteomPodIp             string                 `protobuf:"bytes,8,opt,name=ateom_pod_ip,json=ateomPodIp,proto3" json:"ateom_pod_ip,omitempty"`
	LastSnapshot           string                 `protobuf:"bytes,9,opt,name=last_snapshot,json=lastSnapshot,proto3" json:"last_snapshot,omitempty"`
	InProgressSnapshot     string                 `protobuf:"bytes,10,opt,name=in_progress_snapshot,json=inProgressSnapshot,proto3" json:"in_progress_snapshot,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_ateapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Actor) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Actor) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *Actor) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *Actor) GetStatus() Actor_Status {
	if x != nil {
		return x.Status
	}
	return Actor_STATUS_UNSPECIFIED
}

func (x *Actor) GetAteomPodNamespace() string {
	if x != nil {
		return x.AteomPodNamespace
	}
	return ""
}

func (x *Actor) GetAteomPodName() string {
	if x != nil {
		return x.AteomPodName
	}
	return ""
}

func (x *Actor) GetAteomPodIp() string {
	if x != nil {
		return x.AteomPodIp
	}
	return ""
}

func (x *Actor) GetLastSnapshot() string {
	if x != nil {
		return x.LastSnapshot
	}
	return ""
}

func (x *Actor) GetInProgressSnapshot() string {
	if x != nil {
		return x.InProgressSnapshot
	}
	return ""
}

type GetActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	mi := &file_ateapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{1}
}

func (x *GetActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorResponse) Reset() {
	*x = GetActorResponse{}
	mi := &file_ateapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorResponse) ProtoMessage() {}

func (x *GetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorResponse.ProtoReflect.Descriptor instead.
func (*GetActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{2}
}

func (x *GetActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Request to create a new Actor.
type CreateActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The custom identifier for the new Actor. Must be a valid DNS-1123 label.
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// The namespace of the ActorTemplate to derive from.
	ActorTemplateNamespace string `protobuf:"bytes,2,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	// The name of the ActorTemplate to derive from.
	ActorTemplateName string `protobuf:"bytes,3,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateActorRequest) Reset() {
	*x = CreateActorRequest{}
	mi := &file_ateapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorRequest) ProtoMessage() {}

func (x *CreateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorRequest.ProtoReflect.Descriptor instead.
func (*CreateActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{3}
}

func (x *CreateActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CreateActorRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CreateActorRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

type CreateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorResponse) Reset() {
	*x = CreateActorResponse{}
	mi := &file_ateapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorResponse) ProtoMessage() {}

func (x *CreateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorResponse.ProtoReflect.Descriptor instead.
func (*CreateActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{4}
}

func (x *CreateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type SuspendActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorRequest) Reset() {
	*x = SuspendActorRequest{}
	mi := &file_ateapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorRequest) ProtoMessage() {}

func (x *SuspendActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorRequest.ProtoReflect.Descriptor instead.
func (*SuspendActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{5}
}

func (x *SuspendActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type SuspendActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendActorResponse) Reset() {
	*x = SuspendActorResponse{}
	mi := &file_ateapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendActorResponse) ProtoMessage() {}

func (x *SuspendActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendActorResponse.ProtoReflect.Descriptor instead.
func (*SuspendActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{6}
}

func (x *SuspendActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ResumeActorRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ActorId string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// If true, skip golden snapshot and boot the workload from scratch.
	Boot          bool `protobuf:"varint,2,opt,name=boot,proto3" json:"boot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorRequest) Reset() {
	*x = ResumeActorRequest{}
	mi := &file_ateapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorRequest) ProtoMessage() {}

func (x *ResumeActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorRequest.ProtoReflect.Descriptor instead.
func (*ResumeActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ResumeActorRequest) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type ResumeActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeActorResponse) Reset() {
	*x = ResumeActorResponse{}
	mi := &file_ateapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeActorResponse) ProtoMessage() {}

func (x *ResumeActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeActorResponse.ProtoReflect.Descriptor instead.
func (*ResumeActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type DeleteActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActorRequest) Reset() {
	*x = DeleteActorRequest{}
	mi := &file_ateapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActorRequest) ProtoMessage() {}

func (x *DeleteActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActorRequest.ProtoReflect.Descriptor instead.
func (*DeleteActorRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteActorRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type DeleteActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActorResponse) Reset() {
	*x = DeleteActorResponse{}
	mi := &file_ateapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActorResponse) ProtoMessage() {}

func (x *DeleteActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActorResponse.ProtoReflect.Descriptor instead.
func (*DeleteActorResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{10}
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_ateapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{11}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_ateapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{12}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

type ListActorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	mi := &file_ateapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{13}
}

type ListActorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*Actor               `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	mi := &file_ateapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{14}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

type Worker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerNamespace string                 `protobuf:"bytes,1,opt,name=worker_namespace,json=workerNamespace,proto3" json:"worker_namespace,omitempty"`
	WorkerPool      string                 `protobuf:"bytes,2,opt,name=worker_pool,json=workerPool,proto3" json:"worker_pool,omitempty"`
	WorkerPod       string                 `protobuf:"bytes,3,opt,name=worker_pod,json=workerPod,proto3" json:"worker_pod,omitempty"`
	ActorNamespace  string                 `protobuf:"bytes,4,opt,name=actor_namespace,json=actorNamespace,proto3" json:"actor_namespace,omitempty"`
	ActorTemplate   string                 `protobuf:"bytes,5,opt,name=actor_template,json=actorTemplate,proto3" json:"actor_template,omitempty"`
	ActorId         string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Ip              string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	Version         int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_ateapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{15}
}

func (x *Worker) GetWorkerNamespace() string {
	if x != nil {
		return x.WorkerNamespace
	}
	return ""
}

func (x *Worker) GetWorkerPool() string {
	if x != nil {
		return x.WorkerPool
	}
	return ""
}

func (x *Worker) GetWorkerPod() string {
	if x != nil {
		return x.WorkerPod
	}
	return ""
}

func (x *Worker) GetActorNamespace() string {
	if x != nil {
		return x.ActorNamespace
	}
	return ""
}

func (x *Worker) GetActorTemplate() string {
	if x != nil {
		return x.ActorTemplate
	}
	return ""
}

func (x *Worker) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Worker) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Worker) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DebugClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearRequest) Reset() {
	*x = DebugClearRequest{}
	mi := &file_ateapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearRequest) ProtoMessage() {}

func (x *DebugClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearRequest.ProtoReflect.Descriptor instead.
func (*DebugClearRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{16}
}

type DebugClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugClearResponse) Reset() {
	*x = DebugClearResponse{}
	mi := &file_ateapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugClearResponse) ProtoMessage() {}

func (x *DebugClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugClearResponse.ProtoReflect.Descriptor instead.
func (*DebugClearResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{17}
}

type MintJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      []string               `protobuf:"bytes,1,rep,name=audience,proto3" json:"audience,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTRequest) Reset() {
	*x = MintJWTRequest{}
	mi := &file_ateapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTRequest) ProtoMessage() {}

func (x *MintJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTRequest.ProtoReflect.Descriptor instead.
func (*MintJWTRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{18}
}

func (x *MintJWTRequest) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *MintJWTRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintJWTRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintJWTRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MintJWTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session JWT.  An OIDC Discovery-compatible JWT
	//
	// Claims:
	//
	//   - iss: Issuer - a valid URL where a relying party can fetch the OIDC
	//     discovery documents.
	//   - sub: Subject - a string expressing the identity carried in the
	//
	// credential. Format
	//
	//	`app/${appid}/user/${userid}/session/${sessionid}`.
	//   - aud: Audience - a string identifying the service this token will be used
	//     to authenticate to.
	//   - nbf: Not Before - a numeric unix timestamp
	//   - exp: Expiration - a numeric unix timestamp
	//   - iat: Issued At - a numeric unix timestamp
	//   - `ate.dev`: Ate/Substrate Extension - JSON object
	//   - appID: (string) The Substrate App ID
	//   - userID: (string) The Substrate User ID
	//   - sessionID: (string) The Substrate Session ID
	SessionJwt    string `protobuf:"bytes,1,opt,name=session_jwt,json=sessionJwt,proto3" json:"session_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTResponse) Reset() {
	*x = MintJWTResponse{}
	mi := &file_ateapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTResponse) ProtoMessage() {}

func (x *MintJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTResponse.ProtoReflect.Descriptor instead.
func (*MintJWTResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{19}
}

func (x *MintJWTResponse) GetSessionJwt() string {
	if x != nil {
		return x.SessionJwt
	}
	return ""
}

type MintCertRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Request contains DER encoded bytes of a x509 certificate signing request.
	// The signer will ignore the contents of the CSR except to extract the
	// subject public key.
	CertificateSigningRequest []byte `protobuf:"bytes,4,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MintCertRequest) Reset() {
	*x = MintCertRequest{}
	mi := &file_ateapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertRequest) ProtoMessage() {}

func (x *MintCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertRequest.ProtoReflect.Descriptor instead.
func (*MintCertRequest) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{20}
}

func (x *MintCertRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MintCertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MintCertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MintCertRequest) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.CertificateSigningRequest
	}
	return nil
}

type MintCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response contains a list of DER encoded certificates. The first entry is the
	// leaf certificate, and any remaining entries are intermediates in
	// leaf-to-root order.
	SessionCertificates [][]byte `protobuf:"bytes,1,rep,name=session_certificates,json=sessionCertificates,proto3" json:"session_certificates,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MintCertResponse) Reset() {
	*x = MintCertResponse{}
	mi := &file_ateapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertResponse) ProtoMessage() {}

func (x *MintCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertResponse.ProtoReflect.Descriptor instead.
func (*MintCertResponse) Descriptor() ([]byte, []int) {
	return file_ateapi_proto_rawDescGZIP(), []int{21}
}

func (x *MintCertResponse) GetSessionCertificates() [][]byte {
	if x != nil {
		return x.SessionCertificates
	}
	return nil
}

var File_ateapi_proto protoreflect.FileDescriptor

const file_ateapi_proto_rawDesc = "" +
	"\n" +
	"\fateapi.proto\x12\x06ateapi\"\x9b\x04\n" +
	"\x05Actor\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.ateapi.Actor.StatusR\x06status\x12.\n" +
	"\x13ateom_pod_namespace\x18\x06 \x01(\tR\x11ateomPodNamespace\x12$\n" +
	"\x0eateom_pod_name\x18\a \x01(\tR\fateomPodName\x12 \n" +
	"\fateom_pod_ip\x18\b \x01(\tR\n" +
	"ateomPodIp\x12#\n" +
	"\rlast_snapshot\x18\t \x01(\tR\flastSnapshot\x120\n" +
	"\x14in_progress_snapshot\x18\n" +
	" \x01(\tR\x12inProgressSnapshot\"v\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_RESUMING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x15\n" +
	"\x11STATUS_SUSPENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\",\n" +
	"\x0fGetActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"7\n" +
	"\x10GetActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"\x99\x01\n" +
	"\x12CreateActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x128\n" +
	"\x18actor_template_namespace\x18\x02 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x03 \x01(\tR\x11actorTemplateName\":\n" +
	"\x13CreateActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"0\n" +
	"\x13SuspendActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\";\n" +
	"\x14SuspendActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"C\n" +
	"\x12ResumeActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x12\n" +
	"\x04boot\x18\x02 \x01(\bR\x04boot\":\n" +
	"\x13ResumeActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.ateapi.ActorR\x05actor\"/\n" +
	"\x12DeleteActorRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"\x15\n" +
	"\x13DeleteActorResponse\"\x14\n" +
	"\x12ListWorkersRequest\"?\n" +
	"\x13ListWorkersResponse\x12(\n" +
	"\aworkers\x18\x01 \x03(\v2\x0e.ateapi.WorkerR\aworkers\"\x13\n" +
	"\x11ListActorsRequest\";\n" +
	"\x12ListActorsResponse\x12%\n" +
	"\x06actors\x18\x01 \x03(\v2\r.ateapi.ActorR\x06actors\"\x88\x02\n" +
	"\x06Worker\x12)\n" +
	"\x10worker_namespace\x18\x01 \x01(\tR\x0fworkerNamespace\x12\x1f\n" +
	"\vworker_pool\x18\x02 \x01(\tR\n" +
	"workerPool\x12\x1d\n" +
	"\n" +
	"worker_pod\x18\x03 \x01(\tR\tworkerPod\x12'\n" +
	"\x0factor_namespace\x18\x04 \x01(\tR\x0eactorNamespace\x12%\n" +
	"\x0eactor_template\x18\x05 \x01(\tR\ractorTemplate\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\"\x13\n" +
	"\x11DebugClearRequest\"\x14\n" +
	"\x12DebugClearResponse\"{\n" +
	"\x0eMintJWTRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x03(\tR\baudience\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"2\n" +
	"\x0fMintJWTResponse\x12\x1f\n" +
	"\vsession_jwt\x18\x01 \x01(\tR\n" +
	"sessionJwt\"\xa0\x01\n" +
	"\x0fMintCertRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12>\n" +
	"\x1bcertificate_signing_request\x18\x04 \x01(\fR\x19certificateSigningRequest\"E\n" +
	"\x10MintCertResponse\x121\n" +
	"\x14session_certificates\x18\x01 \x03(\fR\x13sessionCertificates2\xcd\x04\n" +
	"\aControl\x12?\n" +
	"\bGetActor\x12\x17.ateapi.GetActorRequest\x1a\x18.ateapi.GetActorResponse\"\x00\x12H\n" +
	"\vCreateActor\x12\x1a.ateapi.CreateActorRequest\x1a\x1b.ateapi.CreateActorResponse\"\x00\x12K\n" +
	"\fSuspendActor\x12\x1b.ateapi.SuspendActorRequest\x1a\x1c.ateapi.SuspendActorResponse\"\x00\x12H\n" +
	"\vResumeActor\x12\x1a.ateapi.ResumeActorRequest\x1a\x1b.ateapi.ResumeActorResponse\"\x00\x12H\n" +
	"\vDeleteActor\x12\x1a.ateapi.DeleteActorRequest\x1a\x1b.ateapi.DeleteActorResponse\"\x00\x12H\n" +
	"\vListWorkers\x12\x1a.ateapi.ListWorkersRequest\x1a\x1b.ateapi.ListWorkersResponse\"\x00\x12E\n" +
	"\n" +
	"ListActors\x12\x19.ateapi.ListActorsRequest\x1a\x1a.ateapi.ListActorsResponse\"\x00\x12E\n" +
	"\n" +
	"DebugClear\x12\x19.ateapi.DebugClearRequest\x1a\x1a.ateapi.DebugClearResponse\"\x002\x8c\x01\n" +
	"\x0fSessionIdentity\x12:\n" +
	"\aMintJWT\x12\x16.ateapi.MintJWTRequest\x1a\x17.ateapi.MintJWTResponse\x12=\n" +
	"\bMintCert\x12\x17.ateapi.MintCertRequest\x1a\x18.ateapi.MintCertResponseB9Z7github.com/agent-substrate/substrate/pkg/proto/ateapipbb\x06proto3"

var (
	file_ateapi_proto_rawDescOnce sync.Once
	file_ateapi_proto_rawDescData []byte
)

func file_ateapi_proto_rawDescGZIP() []byte {
	file_ateapi_proto_rawDescOnce.Do(func() {
		file_ateapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateapi_proto_rawDesc), len(file_ateapi_proto_rawDesc)))
	})
	return file_ateapi_proto_rawDescData
}

var file_ateapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ateapi_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ateapi_proto_goTypes = []any{
	(Actor_Status)(0),            // 0: ateapi.Actor.Status
	(*Actor)(nil),                // 1: ateapi.Actor
	(*GetActorRequest)(nil),      // 2: ateapi.GetActorRequest
	(*GetActorResponse)(nil),     // 3: ateapi.GetActorResponse
	(*CreateActorRequest)(nil),   // 4: ateapi.CreateActorRequest
	(*CreateActorResponse)(nil),  // 5: ateapi.CreateActorResponse
	(*SuspendActorRequest)(nil),  // 6: ateapi.SuspendActorRequest
	(*SuspendActorResponse)(nil), // 7: ateapi.SuspendActorResponse
	(*ResumeActorRequest)(nil),   // 8: ateapi.ResumeActorRequest
	(*ResumeActorResponse)(nil),  // 9: ateapi.ResumeActorResponse
	(*DeleteActorRequest)(nil),   // 10: ateapi.DeleteActorRequest
	(*DeleteActorResponse)(nil),  // 11: ateapi.DeleteActorResponse
	(*ListWorkersRequest)(nil),   // 12: ateapi.ListWorkersRequest
	(*ListWorkersResponse)(nil),  // 13: ateapi.ListWorkersResponse
	(*ListActorsRequest)(nil),    // 14: ateapi.ListActorsRequest
	(*ListActorsResponse)(nil),   // 15: ateapi.ListActorsResponse
	(*Worker)(nil),               // 16: ateapi.Worker
	(*DebugClearRequest)(nil),    // 17: ateapi.DebugClearRequest
	(*DebugClearResponse)(nil),   // 18: ateapi.DebugClearResponse
	(*MintJWTRequest)(nil),       // 19: ateapi.MintJWTRequest
	(*MintJWTResponse)(nil),      // 20: ateapi.MintJWTResponse
	(*MintCertRequest)(nil),      // 21: ateapi.MintCertRequest
	(*MintCertResponse)(nil),     // 22: ateapi.MintCertResponse
}
var file_ateapi_proto_depIdxs = []int32{
	0,  // 0: ateapi.Actor.status:type_name -> ateapi.Actor.Status
	1,  // 1: ateapi.GetActorResponse.actor:type_name -> ateapi.Actor
	1,  // 2: ateapi.CreateActorResponse.actor:type_name -> ateapi.Actor
	1,  // 3: ateapi.SuspendActorResponse.actor:type_name -> ateapi.Actor
	1,  // 4: ateapi.ResumeActorResponse.actor:type_name -> ateapi.Actor
	16, // 5: ateapi.ListWorkersResponse.workers:type_name -> ateapi.Worker
	1,  // 6: ateapi.ListActorsResponse.actors:type_name -> ateapi.Actor
	2,  // 7: ateapi.Control.GetActor:input_type -> ateapi.GetActorRequest
	4,  // 8: ateapi.Control.CreateActor:input_type -> ateapi.CreateActorRequest
	6,  // 9: ateapi.Control.SuspendActor:input_type -> ateapi.SuspendActorRequest
	8,  // 10: ateapi.Control.ResumeActor:input_type -> ateapi.ResumeActorRequest
	10, // 11: ateapi.Control.DeleteActor:input_type -> ateapi.DeleteActorRequest
	12, // 12: ateapi.Control.ListWorkers:input_type -> ateapi.ListWorkersRequest
	14, // 13: ateapi.Control.ListActors:input_type -> ateapi.ListActorsRequest
	17, // 14: ateapi.Control.DebugClear:input_type -> ateapi.DebugClearRequest
	19, // 15: ateapi.SessionIdentity.MintJWT:input_type -> ateapi.MintJWTRequest
	21, // 16: ateapi.SessionIdentity.MintCert:input_type -> ateapi.MintCertRequest
	3,  // 17: ateapi.Control.GetActor:output_type -> ateapi.GetActorResponse
	5,  // 18: ateapi.Control.CreateActor:output_type -> ateapi.CreateActorResponse
	7,  // 19: ateapi.Control.SuspendActor:output_type -> ateapi.SuspendActorResponse
	9,  // 20: ateapi.Control.ResumeActor:output_type -> ateapi.ResumeActorResponse
	11, // 21: ateapi.Control.DeleteActor:output_type -> ateapi.DeleteActorResponse
	13, // 22: ateapi.Control.ListWorkers:output_type -> ateapi.ListWorkersResponse
	15, // 23: ateapi.Control.ListActors:output_type -> ateapi.ListActorsResponse
	18, // 24: ateapi.Control.DebugClear:output_type -> ateapi.DebugClearResponse
	20, // 25: ateapi.SessionIdentity.MintJWT:output_type -> ateapi.MintJWTResponse
	22, // 26: ateapi.SessionIdentity.MintCert:output_type -> ateapi.MintCertResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ateapi_proto_init() }
func file_ateapi_proto_init() {
	if File_ateapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateapi_proto_rawDesc), len(file_ateapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ateapi_proto_goTypes,
		DependencyIndexes: file_ateapi_proto_depIdxs,
		EnumInfos:         file_ateapi_proto_enumTypes,
		MessageInfos:      file_ateapi_proto_msgTypes,
	}.Build()
	File_ateapi_proto = out.File
	file_ateapi_proto_goTypes = nil
	file_ateapi_proto_depIdxs = nil
}
